//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 04:34:57 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.adligo.org/tests4j/run/xml/io/requirements/v1_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.adligo.tests4j.run.xml.io.requirements.v1_0;
