//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.04 at 03:31:14 AM CST 
//


package org.adligo.tests4j.run.xml.io.requirements.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The term project here corresponds to a 
 * managed project which can
 * be shared (i.e. a git, subversion or cvs project).
 * If a project is program which is intended to 
 * be executed by itself (on a command line)
 * or used directly by itself it may be a 
 * system project (project node under a system_type).
 * 
 * <p>Java class for project_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="project_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="association" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="dependency" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="use_cases_path" type="{http://www.adligo.org/tests4j/run/xml/io/requirements/v1_0}use_cases_path_type"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "project_type", propOrder = {
    "association",
    "dependency",
    "useCasesPath"
})
public class ProjectType {

    protected List<String> association;
    protected List<String> dependency;
    @XmlElement(name = "use_cases_path", required = true)
    protected UseCasesPathType useCasesPath;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the association property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the association property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAssociation() {
        if (association == null) {
            association = new ArrayList<String>();
        }
        return this.association;
    }

    /**
     * Gets the value of the dependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDependency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDependency() {
        if (dependency == null) {
            dependency = new ArrayList<String>();
        }
        return this.dependency;
    }

    /**
     * Gets the value of the useCasesPath property.
     * 
     * @return
     *     possible object is
     *     {@link UseCasesPathType }
     *     
     */
    public UseCasesPathType getUseCasesPath() {
        return useCasesPath;
    }

    /**
     * Sets the value of the useCasesPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseCasesPathType }
     *     
     */
    public void setUseCasesPath(UseCasesPathType value) {
        this.useCasesPath = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
