package org.adligo.tests4j.models.shared.reference_groups.jse;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import org.adligo.tests4j.models.shared.association.I_PackageConstantLookup;
import org.adligo.tests4j.models.shared.reference_groups.jse.v1_8.I_JSE_1_8_LangAnnot;
import org.adligo.tests4j.shared.asserts.reference.NameOnlyReferenceGroup;
import org.adligo.tests4j.shared.asserts.reference.ReferenceGroupBaseDelegate;


/**
 * tThis class represents the latest classes in java.lang.annotation
 * for the latest version JSE version (1_8 on 10/1/2014),
 * allowing any method call/field reference.
 * 
 * partially generated by org.adligo.tests4j_gen.PackageClassNameWriter
 * copy/pasting...
 * Also this class should eventually include the entire api 
 * (public methods and fields), for assertion dependency.
 * 
 * @author scott
 *
 */
public class JSE_LangAnnot extends ReferenceGroupBaseDelegate implements I_JSE_1_8_LangAnnot, I_PackageConstantLookup {
	public static final String JAVA_LANG_ANNOTATION = "java.lang.annotation";
	private static final Map<String,String> CONSTANT_LOOKUP = getConstantLookup();
	public static final Set<String> CLASS_NAMES = CONSTANT_LOOKUP.keySet();
	public static final JSE_LangAnnot INSTANCE = new JSE_LangAnnot();
	
	private static Map<String,String> getConstantLookup() {
		Map<String,String> toRet = new HashMap<>();
		toRet.put("java.lang.annotation.Annotation","ANNOTATION");
		toRet.put("java.lang.annotation.ElementType","ELEMENT_TYPE");
		toRet.put("java.lang.annotation.RetentionPolicy","RETENTION_POLICY");
		toRet.put("java.lang.annotation.AnnotationTypeMismatchException","ANNOTATION_TYPE_MISMATCH_EXCEPTION");
		toRet.put("java.lang.annotation.IncompleteAnnotationException","INCOMPLETE_ANNOTATION_EXCEPTION");
		toRet.put("java.lang.annotation.AnnotationFormatError","ANNOTATION_FORMAT_ERROR");
		toRet.put("java.lang.annotation.Documented","DOCUMENTED");
		toRet.put("java.lang.annotation.Inherited","INHERITED");
		toRet.put("java.lang.annotation.Native","NATIVE");
		toRet.put("java.lang.annotation.Repeatable","REPEATABLE");
		toRet.put("java.lang.annotation.Retention","RETENTION");
		toRet.put("java.lang.annotation.Target","TARGET");
		return Collections.unmodifiableMap(toRet);
	}
	private JSE_LangAnnot() {
		super.setDelegate(new NameOnlyReferenceGroup(CONSTANT_LOOKUP.keySet()));
	}
	@Override
	public String getPackageName() {
		return JAVA_LANG_ANNOTATION;
	}
	@Override
	public String getConstantName(String javaName) {
		return CONSTANT_LOOKUP.get(javaName);
	};
}
