package org.adligo.tests4j.models.shared.reference_groups.jse;

import org.adligo.tests4j.models.shared.association.I_PackageConstantLookupModel;
import org.adligo.tests4j.models.shared.reference_groups.jse.v1_6.JSE_1_6_XmlSax;
import org.adligo.tests4j.models.shared.reference_groups.jse.v1_8.I_JSE_1_8_UtilConcurrent;
import org.adligo.tests4j.models.shared.reference_groups.jse.v1_8.I_JSE_1_8_XmlSax;
import org.adligo.tests4j.shared.asserts.reference.NameOnlyReferenceGroup;
import org.adligo.tests4j.shared.asserts.reference.ReferenceGroupBaseDelegate;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;


/**
 * This class represents the latest classes in java.io
 * for the latest version JSE version (1_8 on 10/1/2014),
 * allowing any method call/field reference.
 * 
 * partially generated by org.adligo.tests4j_gen.console.JSEGroupGen
 * copy/pasting...
 * Also this class should eventually include the entire api 
 * (public methods and fields), for assertion dependency.
 * 
 * @author scott
 *
 */
public class JSE_XmlSax extends ReferenceGroupBaseDelegate  implements I_JSE_1_8_XmlSax, I_PackageConstantLookupModel {
	public static final String ORG_XML_SAX = "org.xml.sax";
	private static final Map<String,String> CONSTANT_LOOKUP = getConstantLookup();
	public static final Set<String> CLASS_NAMES = CONSTANT_LOOKUP.keySet();
	public static final JSE_XmlSax INSTANCE = new JSE_XmlSax();
	
	private JSE_XmlSax() {
    super.setDelegate(new NameOnlyReferenceGroup(CONSTANT_LOOKUP.keySet()));
  };
	
	private static Map<String,String> getConstantLookup() {
		Map<String,String> toRet = new HashMap<>(JSE_1_6_XmlSax.INSTANCE.getModelMap());
		return toRet;
	}

	@Override
	public String getPackageName() {
		return ORG_XML_SAX;
	}

	@Override
	public String getConstantName(String javaName) {
		return CONSTANT_LOOKUP.get(javaName);
	}
	
	@Override
  public Map<String, String> getModelMap() {
    return CONSTANT_LOOKUP;
  };
}
