package org.adligo.tests4j.models.shared.reference_groups.jse.v1_6;

public interface I_JSE_1_6_Math {
	//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		public static final String BIG_DECIMAL = "java.math.BigDecimal";
		public static final String BIG_INTEGER = "java.math.BigInteger";
		public static final String MATH_CONTEXT = "java.math.MathContext";
		public static final String ROUNDING_MODE = "java.math.RoundingMode";

}
