package org.adligo.tests4j.models.shared.reference_groups.jse.v1_6;

public interface I_JSE_1_6_Sql {
	//autogenerated by org.adligo.tests4j_gen.console.JSEGroupGen
		public static final String ARRAY = "java.sql.Array";
		public static final String BLOB = "java.sql.Blob";
		public static final String CALLABLE_STATEMENT = "java.sql.CallableStatement";
		public static final String CLOB = "java.sql.Clob";
		public static final String CONNECTION = "java.sql.Connection";
		public static final String DATABASE_META_DATA = "java.sql.DatabaseMetaData";
		public static final String DRIVER = "java.sql.Driver";
		public static final String NCLOB = "java.sql.NClob";
		public static final String PARAMETER_META_DATA = "java.sql.ParameterMetaData";
		public static final String PREPARED_STATEMENT = "java.sql.PreparedStatement";
		public static final String REF = "java.sql.Ref";
		public static final String RESULT_SET = "java.sql.ResultSet";
		public static final String RESULT_SET_META_DATA = "java.sql.ResultSetMetaData";
		public static final String ROW_ID = "java.sql.RowId";
		public static final String SAVEPOINT = "java.sql.Savepoint";
		public static final String SQLDATA = "java.sql.SQLData";
		public static final String SQLINPUT = "java.sql.SQLInput";
		public static final String SQLOUTPUT = "java.sql.SQLOutput";
		public static final String SQLXML = "java.sql.SQLXML";
		public static final String STATEMENT = "java.sql.Statement";
		public static final String STRUCT = "java.sql.Struct";
		public static final String WRAPPER = "java.sql.Wrapper";
		public static final String DATE = "java.sql.Date";
		public static final String DRIVER_MANAGER = "java.sql.DriverManager";
		public static final String DRIVER_PROPERTY_INFO = "java.sql.DriverPropertyInfo";
		public static final String SQLPERMISSION = "java.sql.SQLPermission";
		public static final String TIME = "java.sql.Time";
		public static final String TIMESTAMP = "java.sql.Timestamp";
		public static final String TYPES = "java.sql.Types";
		public static final String CLIENT_INFO_STATUS = "java.sql.ClientInfoStatus";
		public static final String ROW_ID_LIFETIME = "java.sql.RowIdLifetime";
		public static final String BATCH_UPDATE_EXCEPTION = "java.sql.BatchUpdateException";
		public static final String DATA_TRUNCATION = "java.sql.DataTruncation";
		public static final String SQLCLIENT_INFO_EXCEPTION = "java.sql.SQLClientInfoException";
		public static final String SQLDATA_EXCEPTION = "java.sql.SQLDataException";
		public static final String SQLEXCEPTION = "java.sql.SQLException";
		public static final String SQLFEATURE_NOT_SUPPORTED_EXCEPTION = "java.sql.SQLFeatureNotSupportedException";
		public static final String SQLINTEGRITY_CONSTRAINT_VIOLATION_EXCEPTION = "java.sql.SQLIntegrityConstraintViolationException";
		public static final String SQLINVALID_AUTHORIZATION_SPEC_EXCEPTION = "java.sql.SQLInvalidAuthorizationSpecException";
		public static final String SQLNON_TRANSIENT_CONNECTION_EXCEPTION = "java.sql.SQLNonTransientConnectionException";
		public static final String SQLNON_TRANSIENT_EXCEPTION = "java.sql.SQLNonTransientException";
		public static final String SQLRECOVERABLE_EXCEPTION = "java.sql.SQLRecoverableException";
		public static final String SQLSYNTAX_ERROR_EXCEPTION = "java.sql.SQLSyntaxErrorException";
		public static final String SQLTIMEOUT_EXCEPTION = "java.sql.SQLTimeoutException";
		public static final String SQLTRANSACTION_ROLLBACK_EXCEPTION = "java.sql.SQLTransactionRollbackException";
		public static final String SQLTRANSIENT_CONNECTION_EXCEPTION = "java.sql.SQLTransientConnectionException";
		public static final String SQLTRANSIENT_EXCEPTION = "java.sql.SQLTransientException";
		public static final String SQLWARNING = "java.sql.SQLWarning";

}
