package org.adligo.tests4j.models.shared.reference_groups.jse.v1_6;

public interface I_JSE_1_6_NIO {
	//autogenerated by org.adligo.tests4j_gen.console.JSEGroupGen
  public static final String BUFFER = "java.nio.Buffer";
  public static final String BYTE_BUFFER = "java.nio.ByteBuffer";
  public static final String BYTE_ORDER = "java.nio.ByteOrder";
  public static final String CHAR_BUFFER = "java.nio.CharBuffer";
  public static final String DOUBLE_BUFFER = "java.nio.DoubleBuffer";
  public static final String FLOAT_BUFFER = "java.nio.FloatBuffer";
  public static final String INT_BUFFER = "java.nio.IntBuffer";
  public static final String LONG_BUFFER = "java.nio.LongBuffer";
  public static final String MAPPED_BYTE_BUFFER = "java.nio.MappedByteBuffer";
  public static final String SHORT_BUFFER = "java.nio.ShortBuffer";
  public static final String BUFFER_OVERFLOW_EXCEPTION = "java.nio.BufferOverflowException";
  public static final String BUFFER_UNDERFLOW_EXCEPTION = "java.nio.BufferUnderflowException";
  public static final String INVALID_MARK_EXCEPTION = "java.nio.InvalidMarkException";
  public static final String READ_ONLY_BUFFER_EXCEPTION = "java.nio.ReadOnlyBufferException";
}
