package org.adligo.tests4j.models.shared.reference_groups.jse.v1_6;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import org.adligo.tests4j.models.shared.association.I_PackageConstantLookupModel;
import org.adligo.tests4j.shared.asserts.reference.NameOnlyReferenceGroup;
import org.adligo.tests4j.shared.asserts.reference.ReferenceGroupBaseDelegate;


/**
 * these are constants for the versions
 * of java, the plan is to support at least the 
 * previous 3 minor versions (today on 8/26/2014 that would be 1.8, 1.7, 1.6)
 * 
 * use, use the constant imports.
 * Classes included but removed before the 
 * first version should be removed ASAP, if that ever happens.
 * 
 * Note this doesn't implements JSE_1_7_Lang or JSE_1_8_Lang
 * since I am trying to support all the way back to 1_6
 * (although running 1.8 now).
 * 
 * partially generated by org.adligo.tests4j_gen.console.JSEGroupGen
 * copy/pasting...
 * Also this class should eventually include the entire api 
 * (public methods and fields), for assertion dependency.
 * 
 * @author scott
 *
 */
public class JSE_1_6_XmlSax extends ReferenceGroupBaseDelegate implements I_JSE_1_6_XmlSax, I_PackageConstantLookupModel {
	private static final Map<String,String> CONSTANT_LOOKUP = getConstantLookup();
	public static final JSE_1_6_XmlSax INSTANCE = new JSE_1_6_XmlSax();
	
	private static Map<String,String> getConstantLookup() {
		Map<String,String> toRet = new HashMap<>();
		//autogenerated by org.adligo.tests4j_gen.console.JSEGroupGen
    toRet.put("org.xml.sax.AttributeList","ATTRIBUTE_LIST");
    toRet.put("org.xml.sax.Attributes","ATTRIBUTES");
    toRet.put("org.xml.sax.ContentHandler","CONTENT_HANDLER");
    toRet.put("org.xml.sax.DocumentHandler","DOCUMENT_HANDLER");
    toRet.put("org.xml.sax.DTDHandler","DTDHANDLER");
    toRet.put("org.xml.sax.EntityResolver","ENTITY_RESOLVER");
    toRet.put("org.xml.sax.ErrorHandler","ERROR_HANDLER");
    toRet.put("org.xml.sax.Locator","LOCATOR");
    toRet.put("org.xml.sax.Parser","PARSER");
    toRet.put("org.xml.sax.XMLFilter","XMLFILTER");
    toRet.put("org.xml.sax.XMLReader","XMLREADER");
    toRet.put("org.xml.sax.HandlerBase","HANDLER_BASE");
    toRet.put("org.xml.sax.InputSource","INPUT_SOURCE");
    toRet.put("org.xml.sax.SAXException","SAXEXCEPTION");
    toRet.put("org.xml.sax.SAXNotRecognizedException","SAXNOT_RECOGNIZED_EXCEPTION");
    toRet.put("org.xml.sax.SAXNotSupportedException","SAXNOT_SUPPORTED_EXCEPTION");
    toRet.put("org.xml.sax.SAXParseException","SAXPARSE_EXCEPTION");
		return Collections.unmodifiableMap(toRet);
	}
	private JSE_1_6_XmlSax() {
		super.setDelegate(new NameOnlyReferenceGroup(CONSTANT_LOOKUP.keySet()));
	}
	@Override
	public String getPackageName() {
		return "org.xml.sax";
	}
	@Override
	public String getConstantName(String javaName) {
		return CONSTANT_LOOKUP.get(javaName);
	}
	@Override
	public Map<String, String> getModelMap() {
		return CONSTANT_LOOKUP;
	};
}
