package org.adligo.tests4j.models.shared.reference_groups.jse.v1_6;

import org.adligo.tests4j.models.shared.association.I_PackageConstantLookupModel;
import org.adligo.tests4j.shared.asserts.reference.NameOnlyReferenceGroup;
import org.adligo.tests4j.shared.asserts.reference.ReferenceGroupBaseDelegate;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;


/**
 * these are constants for the versions
 * of java, the plan is to support at least the 
 * previous 3 minor versions (today on 8/26/2014 that would be 1.8, 1.7, 1.6)
 * 
 * use, use the constant imports.
 * Classes included but removed before the 
 * first version should be removed ASAP, if that ever happens.
 * 
 * Note this doesn't implements JSE_1_7_Lang or JSE_1_8_Lang
 * since I am trying to support all the way back to 1_6
 * (although running 1.8 now).
 * 
 * partially generated by org.adligo.tests4j_gen.console.JSEGroupGen
 * copy/pasting...
 * Also this class should eventually include the entire api 
 * (public methods and fields), for assertion dependency.
 * 
 * @author scott
 *
 */
public class JSE_1_6_XmlSaxExt extends ReferenceGroupBaseDelegate implements I_JSE_1_6_XmlSaxExt, I_PackageConstantLookupModel {
	private static final Map<String,String> CONSTANT_LOOKUP = getConstantLookup();
	public static final JSE_1_6_XmlSaxExt INSTANCE = new JSE_1_6_XmlSaxExt();
	
	private static Map<String,String> getConstantLookup() {
		Map<String,String> toRet = new HashMap<>();
		//autogenerated by org.adligo.tests4j_gen.console.JSEGroupGen
    toRet.put("org.xml.sax.ext.Attributes2","ATTRIBUTES2");
    toRet.put("org.xml.sax.ext.DeclHandler","DECL_HANDLER");
    toRet.put("org.xml.sax.ext.LexicalHandler","LEXICAL_HANDLER");
    toRet.put("org.xml.sax.ext.Locator2","LOCATOR2");
    toRet.put("org.xml.sax.ext.Attributes2Impl","ATTRIBUTES2_IMPL");
    toRet.put("org.xml.sax.ext.DefaultHandler2","DEFAULT_HANDLER2");
    toRet.put("org.xml.sax.ext.Locator2Impl","LOCATOR2_IMPL");
		return Collections.unmodifiableMap(toRet);
	}
	private JSE_1_6_XmlSaxExt() {
		super.setDelegate(new NameOnlyReferenceGroup(CONSTANT_LOOKUP.keySet()));
	}
	@Override
	public String getPackageName() {
		return "org.xml.sax.ext";
	}
	@Override
	public String getConstantName(String javaName) {
		return CONSTANT_LOOKUP.get(javaName);
	}
	@Override
	public Map<String, String> getModelMap() {
		return CONSTANT_LOOKUP;
	};
}
