package org.adligo.tests4j.models.shared.dependency_groups.jse.v1_7;

public interface JSE_1_7_Log {
	//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		public static final String FILTER = "java.util.logging.Filter";
		public static final String CONSOLE_HANDLER = "java.util.logging.ConsoleHandler";
		public static final String ERROR_MANAGER = "java.util.logging.ErrorManager";
		public static final String FILE_HANDLER = "java.util.logging.FileHandler";
		public static final String FORMATTER = "java.util.logging.Formatter";
		public static final String HANDLER = "java.util.logging.Handler";
		public static final String LEVEL = "java.util.logging.Level";
		public static final String LOGGER = "java.util.logging.Logger";
		public static final String LOGGING_PERMISSION = "java.util.logging.LoggingPermission";
		public static final String LOG_MANAGER = "java.util.logging.LogManager";
		public static final String LOG_RECORD = "java.util.logging.LogRecord";
		public static final String MEMORY_HANDLER = "java.util.logging.MemoryHandler";
		public static final String SIMPLE_FORMATTER = "java.util.logging.SimpleFormatter";
		public static final String SOCKET_HANDLER = "java.util.logging.SocketHandler";
		public static final String STREAM_HANDLER = "java.util.logging.StreamHandler";
		public static final String XMLFORMATTER = "java.util.logging.XMLFormatter";

}
