//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.19 at 12:05:25 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.adligo.org/tests4j/run/xml/io/params/v1_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.adligo.tests4j.run.xml.io.params.v1_0;
