//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.04 at 03:31:14 AM CST 
//


package org.adligo.tests4j.run.xml.io.params.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for params_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="params_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="trial" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="selection" type="{http://www.adligo.org/tests4j/run/xml/io/params/v1_0}selection_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="log" type="{http://www.adligo.org/tests4j/run/xml/io/params/v1_0}log_state_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="remote" type="{http://www.adligo.org/tests4j/run/xml/io/params/v1_0}remote_info_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="metaTrial" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="metaTrialParamsFactory" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="trialParamsFactory" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="coveragePluginFactory" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="recommendedTrialThreads"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *             &lt;minInclusive value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="recommendedRemoteThreads"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *             &lt;minInclusive value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="recommendedSetupThreads"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *             &lt;minInclusive value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="evaluatorLookup" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "params_type", propOrder = {
    "trial",
    "selection",
    "log",
    "remote"
})
public class ParamsType {

    protected List<String> trial;
    protected List<SelectionType> selection;
    protected List<LogStateType> log;
    protected List<RemoteInfoType> remote;
    @XmlAttribute(name = "metaTrial")
    protected String metaTrial;
    @XmlAttribute(name = "metaTrialParamsFactory")
    protected String metaTrialParamsFactory;
    @XmlAttribute(name = "trialParamsFactory")
    protected String trialParamsFactory;
    @XmlAttribute(name = "coveragePluginFactory")
    protected String coveragePluginFactory;
    @XmlAttribute(name = "recommendedTrialThreads")
    protected Integer recommendedTrialThreads;
    @XmlAttribute(name = "recommendedRemoteThreads")
    protected Integer recommendedRemoteThreads;
    @XmlAttribute(name = "recommendedSetupThreads")
    protected Integer recommendedSetupThreads;
    @XmlAttribute(name = "evaluatorLookup")
    protected String evaluatorLookup;

    /**
     * Gets the value of the trial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTrial() {
        if (trial == null) {
            trial = new ArrayList<String>();
        }
        return this.trial;
    }

    /**
     * Gets the value of the selection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectionType }
     * 
     * 
     */
    public List<SelectionType> getSelection() {
        if (selection == null) {
            selection = new ArrayList<SelectionType>();
        }
        return this.selection;
    }

    /**
     * Gets the value of the log property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the log property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLog().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LogStateType }
     * 
     * 
     */
    public List<LogStateType> getLog() {
        if (log == null) {
            log = new ArrayList<LogStateType>();
        }
        return this.log;
    }

    /**
     * Gets the value of the remote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RemoteInfoType }
     * 
     * 
     */
    public List<RemoteInfoType> getRemote() {
        if (remote == null) {
            remote = new ArrayList<RemoteInfoType>();
        }
        return this.remote;
    }

    /**
     * Gets the value of the metaTrial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaTrial() {
        return metaTrial;
    }

    /**
     * Sets the value of the metaTrial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaTrial(String value) {
        this.metaTrial = value;
    }

    /**
     * Gets the value of the metaTrialParamsFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaTrialParamsFactory() {
        return metaTrialParamsFactory;
    }

    /**
     * Sets the value of the metaTrialParamsFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaTrialParamsFactory(String value) {
        this.metaTrialParamsFactory = value;
    }

    /**
     * Gets the value of the trialParamsFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrialParamsFactory() {
        return trialParamsFactory;
    }

    /**
     * Sets the value of the trialParamsFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrialParamsFactory(String value) {
        this.trialParamsFactory = value;
    }

    /**
     * Gets the value of the coveragePluginFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoveragePluginFactory() {
        return coveragePluginFactory;
    }

    /**
     * Sets the value of the coveragePluginFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoveragePluginFactory(String value) {
        this.coveragePluginFactory = value;
    }

    /**
     * Gets the value of the recommendedTrialThreads property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecommendedTrialThreads() {
        return recommendedTrialThreads;
    }

    /**
     * Sets the value of the recommendedTrialThreads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecommendedTrialThreads(Integer value) {
        this.recommendedTrialThreads = value;
    }

    /**
     * Gets the value of the recommendedRemoteThreads property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecommendedRemoteThreads() {
        return recommendedRemoteThreads;
    }

    /**
     * Sets the value of the recommendedRemoteThreads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecommendedRemoteThreads(Integer value) {
        this.recommendedRemoteThreads = value;
    }

    /**
     * Gets the value of the recommendedSetupThreads property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecommendedSetupThreads() {
        return recommendedSetupThreads;
    }

    /**
     * Sets the value of the recommendedSetupThreads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecommendedSetupThreads(Integer value) {
        this.recommendedSetupThreads = value;
    }

    /**
     * Gets the value of the evaluatorLookup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvaluatorLookup() {
        return evaluatorLookup;
    }

    /**
     * Sets the value of the evaluatorLookup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvaluatorLookup(String value) {
        this.evaluatorLookup = value;
    }

}
