package org.adligo.tests4j.models.shared.dependency_groups.jse;

public interface JSE_1_6_Lang {

	//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		//feel free to contribute earlier or older version
		public static final String APPENDABLE = "java.lang.Appendable";
		public static final String CHAR_SEQUENCE = "java.lang.CharSequence";
		public static final String CLONEABLE = "java.lang.Cloneable";
		public static final String COMPARABLE = "java.lang.Comparable";
		public static final String ITERABLE = "java.lang.Iterable";
		public static final String READABLE = "java.lang.Readable";
		public static final String RUNNABLE = "java.lang.Runnable";
		public static final String THREAD_UNCAUGHT_EXCEPTION_HANDLER = "java.lang.Thread$UncaughtExceptionHandler";
		
		public static final String BOOLEAN = "java.lang.Boolean";
		public static final String BYTE = "java.lang.Byte";
		public static final String CHARACTER = "java.lang.Character";
		public static final String CHARACTER_SUBSET = "java.lang.Character$Subset";
		public static final String CHARACTER_UNICODE_BLOCK = "java.lang.Character$UnicodeBlock";
		public static final String CLASS = "java.lang.Class";
		public static final String CLASS_LOADER = "java.lang.ClassLoader";
		public static final String CLASS_VALUE = "java.lang.ClassValue";
		public static final String COMPILER = "java.lang.Compiler";
		public static final String DOUBLE = "java.lang.Double";
		public static final String ENUM = "java.lang.Enum";
		public static final String FLOAT = "java.lang.Float";
		public static final String INHERITABLE_THREAD_LOCAL = "java.lang.InheritableThreadLocal";
		public static final String INTEGER = "java.lang.Integer";
		public static final String LONG = "java.lang.Long";
		public static final String MATH = "java.lang.Math";
		public static final String NUMBER = "java.lang.Number";
		public static final String OBJECT = "java.lang.Object";
		public static final String PACKAGE = "java.lang.Package";
		public static final String PROCESS = "java.lang.Process";
		public static final String PROCESS_BUILDER = "java.lang.ProcessBuilder";
		public static final String RUNTIME = "java.lang.Runtime";
		public static final String RUNTIME_PERMISSION = "java.lang.RuntimePermission";
		public static final String SECURITY_MANAGER = "java.lang.SecurityManager";
		public static final String SHORT = "java.lang.Short";
		public static final String STACK_TRACE_ELEMENT = "java.lang.StackTraceElement";
		public static final String STRICT_MATH = "java.lang.StrictMath";
		public static final String STRING = "java.lang.String";
		public static final String STRING_BUFFER = "java.lang.StringBuffer";
		public static final String STRING_BUILDER = "java.lang.StringBuilder";
		public static final String SYSTEM = "java.lang.System";
		public static final String THREAD = "java.lang.Thread";
		public static final String THREAD_GROUP = "java.lang.ThreadGroup";
		public static final String THREAD_LOCAL = "java.lang.ThreadLocal";
		public static final String THROWABLE = "java.lang.Throwable";
		public static final String VOID = "java.lang.Void";
		
		
		public static final String THREAD_STATE = "java.lang.Thread$State";
		
		public static final String ARITHMETIC_EXCEPTION = "java.lang.ArithmeticException";
		public static final String ARRAY_INDEX_OUT_OF_BOUNDS_EXCEPTION = "java.lang.ArrayIndexOutOfBoundsException";
		public static final String ARRAY_STORE_EXCEPTION = "java.lang.ArrayStoreException";
		public static final String CLASS_CAST_EXCEPTION = "java.lang.ClassCastException";
		public static final String CLASS_NOT_FOUND_EXCEPTION = "java.lang.ClassNotFoundException";
		public static final String CLONE_NOT_SUPPORTED_EXCEPTION = "java.lang.CloneNotSupportedException";
		public static final String ENUM_CONSTANT_NOT_PRESENT_EXCEPTION = "java.lang.EnumConstantNotPresentException";
		public static final String EXCEPTION = "java.lang.Exception";
		public static final String ILLEGAL_ACCESS_EXCEPTION = "java.lang.IllegalAccessException";
		public static final String ILLEGAL_ARGUMENT_EXCEPTION = "java.lang.IllegalArgumentException";
		public static final String ILLEGAL_MONITOR_STATE_EXCEPTION = "java.lang.IllegalMonitorStateException";
		public static final String ILLEGAL_STATE_EXCEPTION = "java.lang.IllegalStateException";
		public static final String ILLEGAL_THREAD_STATE_EXCEPTION = "java.lang.IllegalThreadStateException";
		public static final String INDEX_OUT_OF_BOUNDS_EXCEPTION = "java.lang.IndexOutOfBoundsException";
		public static final String INSTANTIATION_EXCEPTION = "java.lang.InstantiationException";
		public static final String INTERRUPTED_EXCEPTION = "java.lang.InterruptedException";
		public static final String NEGATIVE_ARRAY_SIZE_EXCEPTION = "java.lang.NegativeArraySizeException";
		public static final String NO_SUCH_FIELD_EXCEPTION = "java.lang.NoSuchFieldException";
		public static final String NO_SUCH_METHOD_EXCEPTION = "java.lang.NoSuchMethodException";
		public static final String NULL_POINTER_EXCEPTION = "java.lang.NullPointerException";
		public static final String NUMBER_FORMAT_EXCEPTION = "java.lang.NumberFormatException";
		public static final String REFLECTIVE_OPERATION_EXCEPTION = "java.lang.ReflectiveOperationException";
		public static final String RUNTIME_EXCEPTION = "java.lang.RuntimeException";
		public static final String SECURITY_EXCEPTION = "java.lang.SecurityException";
		public static final String STRING_INDEX_OUT_OF_BOUNDS_EXCEPTION = "java.lang.StringIndexOutOfBoundsException";
		public static final String TYPE_NOT_PRESENT_EXCEPTION = "java.lang.TypeNotPresentException";
		public static final String UNSUPPORTED_OPERATION_EXCEPTION = "java.lang.UnsupportedOperationException";
		
		public static final String ABSTRACT_METHOD_ERROR = "java.lang.AbstractMethodError";
		public static final String ASSERTION_ERROR = "java.lang.AssertionError";
		public static final String CLASS_CIRCULARITY_ERROR = "java.lang.ClassCircularityError";
		public static final String CLASS_FORMAT_ERROR = "java.lang.ClassFormatError";
		public static final String ERROR = "java.lang.Error";
		public static final String EXCEPTION_IN_INITIALIZER_ERROR = "java.lang.ExceptionInInitializerError";
		public static final String ILLEGAL_ACCESS_ERROR = "java.lang.IllegalAccessError";
		public static final String INCOMPATIBLE_CLASS_CHANGE_ERROR = "java.lang.IncompatibleClassChangeError";
		public static final String INSTANTIATION_ERROR = "java.lang.InstantiationError";
		public static final String INTERNAL_ERROR = "java.lang.InternalError";
		public static final String LINKAGE_ERROR = "java.lang.LinkageError";
		public static final String NO_CLASS_DEF_FOUND_ERROR = "java.lang.NoClassDefFoundError";
		public static final String NO_SUCH_FIELD_ERROR = "java.lang.NoSuchFieldError";
		public static final String NO_SUCH_METHOD_ERROR = "java.lang.NoSuchMethodError";
		public static final String OUT_OF_MEMORY_ERROR = "java.lang.OutOfMemoryError";
		public static final String STACK_OVERFLOW_ERROR = "java.lang.StackOverflowError";
		public static final String THREAD_DEATH = "java.lang.ThreadDeath";
		public static final String UNKNOWN_ERROR = "java.lang.UnknownError";
		public static final String UNSATISFIED_LINK_ERROR = "java.lang.UnsatisfiedLinkError";
		public static final String UNSUPPORTED_CLASS_VERSION_ERROR = "java.lang.UnsupportedClassVersionError";
		public static final String VERIFY_ERROR = "java.lang.VerifyError";
		public static final String VIRTUAL_MACHINE_ERROR = "java.lang.VirtualMachineError";
		
		public static final String DEPRECATED = "java.lang.Deprecated";
		public static final String OVERRIDE = "java.lang.Override";
		public static final String SUPPRESS_WARNINGS = "java.lang.SuppressWarnings";
}
