package org.adligo.tests4j.models.shared.dependency_groups.jse.v1_8;

import org.adligo.tests4j.models.shared.dependency_groups.jse.v1_7.JSE_1_7_Lang;

public interface JSE_1_8_Lang extends JSE_1_7_Lang  {

	//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		//feel free to contribute earlier or older version
	public static final String FUNCTIONAL_INTERFACE = "java.lang.FunctionalInterface";
	
}
