package org.adligo.tests4j.models.dependency_groups.jse;

public interface JSE_1_8_Lang extends JSE_1_7_Lang  {

	//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		//feel free to contribute earlier or older version
	public static final String FUNCTIONAL_INTERFACE = "java.lang.FunctionalInterface";
	
}
