package org.adligo.tests4j.models.shared.dependency_groups;

public class JSE_1_7_LangAnnot {
	//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		public static final String ANNOTATION = "java.lang.annotation.Annotation";
		public static final String ELEMENT_TYPE = "java.lang.annotation.ElementType";
		public static final String RETENTION_POLICY = "java.lang.annotation.RetentionPolicy";
		public static final String ANNOTATION_TYPE_MISMATCH_EXCEPTION = "java.lang.annotation.AnnotationTypeMismatchException";
		public static final String INCOMPLETE_ANNOTATION_EXCEPTION = "java.lang.annotation.IncompleteAnnotationException";
		public static final String ANNOTATION_FORMAT_ERROR = "java.lang.annotation.AnnotationFormatError";
		public static final String DOCUMENTED = "java.lang.annotation.Documented";
		public static final String INHERITED = "java.lang.annotation.Inherited";
		public static final String RETENTION = "java.lang.annotation.Retention";
		public static final String TARGET = "java.lang.annotation.Target";
		public static final JSE_1_7_LangAnnot INSTANCE = new JSE_1_7_LangAnnot();
		
		private JSE_1_7_LangAnnot() {}
}
