package org.adligo.tests4j.models.shared.dependency_groups;

public class JSE_1_7_Math {
	//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		public static final String BIG_DECIMAL = "java.math.BigDecimal";
		public static final String BIG_INTEGER = "java.math.BigInteger";
		public static final String MATH_CONTEXT = "java.math.MathContext";
		public static final String ROUNDING_MODE = "java.math.RoundingMode";
		public static final JSE_1_7_Math INSTANCE = new JSE_1_7_Math();
		
		private JSE_1_7_Math() {}
}
